#!/usr/bin/env php
<?php

if (!file_exists(__DIR__.'/config.php')) {
    die('No configuration file exists.');
}

$config = require __DIR__.'/config.php';

// Create connection
$database = new mysqli(
    $config['db_host'],
    $config['db_user'],
    $config['db_pass'],
    $config['db_name']
);

// Check connection
if ($database->connect_error) {
    die('Connection failed: '.$database->connect_error);
}

// If this is enabled, it will send an email on startup to notify you that the service is running.
$notifyOnStart = true;

while (true) {
    // Get info from database to check which block you won last
    $query = 'SELECT * FROM masternode WHERE ip = \''.$config['ip_address'].'\'';

    if (!$result = $database->query($query)) {
        die($database->error);
    }

    $myLastBlock = null;
    while ($row = $result->fetch_array()) {
        $myLastBlock = $row['last_won'];
    }

    // Get info from database to get current block height of the chain
    $currentBlock = $database->query('SELECT MAX(height) as max_height FROM blocks');

    if (!$currentBlock) {
        die($database->error);
    }

    $lastBlock = 'Unknown';
    while ($row = $currentBlock->fetch_array()) {
        $lastBlock = $row['max_height'];
    }

    // Get your masternode balance provided by the public key
    $url = 'http://'.$config['ip_address'].'/api.php?q=getBalance&public_key='.$config['public_key'];
    $balanceResult = file_get_contents($url);

    if (!$balanceResult) {
        die($database->error);
    }

    $balance = json_decode($balanceResult);
    $myBalance = $balance->data;

    // Create the body for the notification email
    $body = 'Your IP # '.$config['ip_address'].' last reward block is : '.$myLastBlock.
        ', Block Height is : '.$lastBlock.', Your Balance is : '.$myBalance;

    // Compare your last block won to the current block height to see if you won this block, then email you if you did.
    $tempFile = __DIR__.'/tmp';
    $lastNotified = file_get_contents($tempFile);

    if ($myLastBlock === $lastBlock && $lastBlock !== $lastNotified) {
        mail($config['mail_to'], 'You Won A Block', $body, 'From: '.$config['mail_from']);
        unlink($tempFile);
        file_put_contents($tempFile, $lastBlock);
    } else {
        // Delete hash below to test your email
        // mail($config['mail_to'], 'You Did Not Win Block # '.$lastBlock, $body, 'From: '.$config['mail_from']);
    }

    if ($notifyOnStart) {
        mail(
            $config['mail_to'],
            'Masternode Reward Notification Service is started. '.$lastBlock,
            $body,
            'From: '.$config['mail_from']
        );
        $notifyOnStart = false;

        echo 'Startup notification email sent.';
    }

    // The amount of time to wait before polling database again, keep under 30ish to catch occasional short block times.
    sleep(20);
}

$database->close();
